name: "Pull Request / Labeled"

# -----------------------------------------------------------------------------
#
# Fired when a pull request is labeled.
#
# -----------------------------------------------------------------------------

on:
  merge_group:
  push:
    branches:
      - main
      - master
  pull_request:
    types:
      - labeled

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  check:
    name: "Maintainer Approval"
    runs-on: ubuntu-latest

    steps:
      - run: exit 0
