name: "Semgrep"

# This workflow will run after a pull request is opened or updated, assuming the pull request is labeled with "Vetted".

on:
  workflow_run:
    workflows:
      - "Pull Request / Run Checks"
    types:
      - completed

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  semgrep:
    name: "Run Checks"
    runs-on: ubuntu-latest

    container:
      image: returntocorp/semgrep

    steps:
      # Not a pull request. Success.
      - if: ${{ github.event_name != 'pull_request' }}
        run: exit 0

      # Dependabot. Success.
      - if: ${{ github.actor == 'dependabot[bot]' }}
        run: exit 0

      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - run: semgrep ci
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
