name: Unit Tests

on:
  pull_request_target:
    types: [labeled]
  push:
    branches: [main]

permissions:
  contents: write
  pull-requests: write

jobs:
  test-pest:
    name: Unit
    runs-on: ubuntu-latest
    continue-on-error: true

    if: github.event.label.name == 'run' || github.ref_name == 'main'

    strategy:
      max-parallel: 10
      matrix:
        php: ["8.1", "8.2"]

    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: pcov
          extensions: mbstring, openssl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v3

      - run: composer install --prefer-dist
      - run: vendor/bin/pest --coverage-clover coverage/coverage.xml --no-interaction --order-by random

      - if: (matrix.php == '8.2')
        uses: codecov/codecov-action@v2
        with:
          directory: coverage
